### ISSUE TITLE
System.Data.SqlServerCe.SqlCeException (0x80004005): The specified table does not exist. [ sysobjects ] after changing to SQL Server Compact

### ISSUE THREAD

**Issue by davidpodhola** [amirrajan/Oak#30]
If I change Web.Config, Query.cs and Massive.cs to connect to SQL Server Compact (connection string in Web.config, Sql* classes to SqlCe* classes and _providerName = "System.Data.SqlServerCe.4.0" in Massive), I get  The specified table does not exist. [ sysobjects ] 

   at Oak.Query.ExecuteReader(String query, ConnectionProfile connectionProfile)
 in c:\Users\david.podhola\Documents\Visual Studio 2012\Projects\Blog\Blog\Oak\Q
uery.cs:line 46
   at Oak.Seed.DropAllForeignKeys() in c:\Users\david.podhola\Documents\Visual S
tudio 2012\Projects\Blog\Blog\Oak\Seed.cs:line 185
   at Oak.Seed.PurgeDb() in c:\Users\david.podhola\Documents\Visual Studio 2012\
Projects\Blog\Blog\Oak\Seed.cs:line 142

after running "rake sample"

Probably should be change according to http://support.microsoft.com/kb/272210

**Comment by amirrajan** [comment]
will not fix
